import { User } from './user';

export const users: User[] = [
  // {
  //     CorreoElectronico: 'john.doe@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: true,
  //     Nombre: 'John',
  //     ApellidoPaterno: 'Doe',
  //     ApellidoMaterno: 'Smith',
  //     Telefono: '123-456-7890',
  //     Menu: 'Menu1',
  //     FechaInactiva: '2023-12-31',
  //     Admin: false,
  //     Empleado: 'E123',
  //     Sucursal: 'Sucursal1'
  // },
  // {
  //     CorreoElectronico: 'jane.doe@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: true,
  //     Nombre: 'Jane',
  //     ApellidoPaterno: 'Doe',
  //     ApellidoMaterno: 'Johnson',
  //     Telefono: '123-456-7891',
  //     Menu: 'Menu2',
  //     FechaInactiva: '2023-12-31',
  //     Admin: true,
  //     Empleado: 'E124',
  //     Sucursal: 'Sucursal2'
  // },
  // {
  //     CorreoElectronico: 'alice.smith@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: false,
  //     Nombre: 'Alice',
  //     ApellidoPaterno: 'Smith',
  //     ApellidoMaterno: 'Brown',
  //     Telefono: '123-456-7892',
  //     Menu: 'Menu3',
  //     FechaInactiva: '2023-12-31',
  //     Admin: false,
  //     Empleado: 'E125',
  //     Sucursal: 'Sucursal3'
  // },
  // {
  //     CorreoElectronico: 'bob.johnson@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: true,
  //     Nombre: 'Bob',
  //     ApellidoPaterno: 'Johnson',
  //     ApellidoMaterno: 'Williams',
  //     Telefono: '123-456-7893',
  //     Menu: 'Menu1',
  //     FechaInactiva: '2023-12-31',
  //     Admin: false,
  //     Empleado: 'E126',
  //     Sucursal: 'Sucursal1'
  // },
  // {
  //     CorreoElectronico: 'carol.williams@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: true,
  //     Nombre: 'Carol',
  //     ApellidoPaterno: 'Williams',
  //     ApellidoMaterno: 'Jones',
  //     Telefono: '123-456-7894',
  //     Menu: 'Menu2',
  //     FechaInactiva: '2023-12-31',
  //     Admin: true,
  //     Empleado: 'E127',
  //     Sucursal: 'Sucursal2'
  // },
  // {
  //     CorreoElectronico: 'dave.brown@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: false,
  //     Nombre: 'Dave',
  //     ApellidoPaterno: 'Brown',
  //     ApellidoMaterno: 'Garcia',
  //     Telefono: '123-456-7895',
  //     Menu: 'Menu3',
  //     FechaInactiva: '2023-12-31',
  //     Admin: false,
  //     Empleado: 'E128',
  //     Sucursal: 'Sucursal3'
  // },
  // {
  //     CorreoElectronico: 'eve.jones@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: true,
  //     Nombre: 'Eve',
  //     ApellidoPaterno: 'Jones',
  //     ApellidoMaterno: 'Martinez',
  //     Telefono: '123-456-7896',
  //     Menu: 'Menu1',
  //     FechaInactiva: '2023-12-31',
  //     Admin: false,
  //     Empleado: 'E129',
  //     Sucursal: 'Sucursal1'
  // },
  // {
  //     CorreoElectronico: 'frank.martinez@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: true,
  //     Nombre: 'Frank',
  //     ApellidoPaterno: 'Martinez',
  //     ApellidoMaterno: 'Hernandez',
  //     Telefono: '123-456-7897',
  //     Menu: 'Menu2',
  //     FechaInactiva: '2023-12-31',
  //     Admin: true,
  //     Empleado: 'E130',
  //     Sucursal: 'Sucursal2'
  // },
  // {
  //     CorreoElectronico: 'grace.hernandez@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: false,
  //     Nombre: 'Grace',
  //     ApellidoPaterno: 'Hernandez',
  //     ApellidoMaterno: 'Lopez',
  //     Telefono: '123-456-7898',
  //     Menu: 'Menu3',
  //     FechaInactiva: '2023-12-31',
  //     Admin: false,
  //     Empleado: 'E131',
  //     Sucursal: 'Sucursal3'
  // },
  // {
  //     CorreoElectronico: 'henry.lopez@example.com',
  //     Contraseña: 'password123',
  //     Habilitado: true,
  //     Nombre: 'Henry',
  //     ApellidoPaterno: 'Lopez',
  //     ApellidoMaterno: 'Gonzalez',
  //     Telefono: '123-456-7899',
  //     Menu: 'Menu1',
  //     FechaInactiva: '2023-12-31',
  //     Admin: false,
  //     Empleado: 'E132',
  //     Sucursal: 'Sucursal1'
  // }
];
