import { RouteInfo } from "./vertical-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Home",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "/starter",
    title: "Starter Page",
    icon: "mdi mdi-crop-free",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "UI",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "component",
    title: "UI Elements",
    icon: "mdi mdi-widgets",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "/component/accordion",
        title: "Accordion",
        icon: "mdi mdi-equal",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/alert",
        title: "Alert",
        icon: "mdi mdi-message-bulleted",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/buttons",
        title: "Button",
        icon: "mdi mdi-toggle-switch",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/carousel",
        title: "Carousel",
        icon: "mdi mdi-view-carousel",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/dropdown",
        title: "Dropdown",
        icon: "mdi mdi-arrange-bring-to-front",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/modal",
        title: "Modal",
        icon: "mdi mdi-tablet",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/nav",
        title: "Nav",
        icon: "mdi mdi-sort-variant",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/notifier",
        title: "Notifier",
        icon: "mdi mdi-auto-fix",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/pagination",
        title: "Pagination",
        icon: "mdi mdi-backburger",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/poptool",
        title: "Popover & Tooltip",
        icon: "mdi mdi-image-filter-vintage",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/progressbar",
        title: "Progressbar",
        icon: "mdi mdi-poll",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/rating",
        title: "Ratings",
        icon: "mdi mdi-bandcamp",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/timepicker",
        title: "Timepicker",
        icon: "mdi mdi-calendar-clock",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/toast",
        title: "Toast",
        icon: "mdi mdi-arrange-bring-forward",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },


  {
    path: "mlevel",
    title: "Menu Levels",
    icon: "mdi mdi-notification-clear-all",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "",
        title: "Second Level",
        icon: "mdi mdi-octagram",
        class: "",
        extralink: true,
        submenu: [],
      },
      {
        path: "/second",
        title: "Second Child",
        icon: "mdi mdi-octagram",
        class: "has-arrow",
        extralink: false,
        submenu: [
          {
            path: "/thirdone",
            title: "Third 1.1",
            icon: "mdi mdi-playlist-plus",
            class: "",
            extralink: false,
            submenu: [],
          },
          {
            path: "/thirdtwo",
            title: "Third 1.2",
            icon: "mdi mdi-playlist-plus",
            class: "",
            extralink: false,
            submenu: [],
          },
        ],
      },
    ],
  },
];
